version: "3"
services:
  api:
    build: .
    ports:
      - 8080:3001
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: task-managment
      DB_PORT: 5432
      DB_HOST: db
  db:
    image: postgres:alpine3.14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-managment
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - ./database:/var/lib/postgresql/data
volumes:
  database:

